name = "runpass"
type = "webpack"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-01-31"
webpack_config = "webpack.config.js"

[env.production]
# The ID of the domain to deploying to
zone_id = "28de50e1f2392491729f9ccb9d189279"

# The route pattern your Workers application will be served at
route = "prod-api.getrunpass.com/*"
logpush = true

[env.development]
# The ID of the domain to deploying to
zone_id = "28de50e1f2392491729f9ccb9d189279"

# The route pattern your Workers application will be served at
route = "dev-api.getrunpass.com/*"
logpush = true