name = "runpass"
main = "src/index.ts"

workers_dev = true
compatibility_date = "2026-04-30"
compatibility_flags = ["nodejs_compat"]

[[rules]]
type = "Text"
globs = ["**/*.pem"]
fallthrough = true

[[rules]]
type = "Data"
globs = ["**/*.png"]
fallthrough = true

[env.production]
# The route pattern your Workers application will be served at
route = "prod-api.getrunpass.com/*"
logpush = true
compatibility_flags = ["nodejs_compat"]

[env.development]
# The route pattern your Workers application will be served at
route = "dev-api.getrunpass.com/*"
logpush = true
compatibility_flags = ["nodejs_compat"]
