name: publish cloudflare worker

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: npm
          cache-dependency-path: cloudflare-worker/package-lock.json

      - run: npm ci
        working-directory: ./cloudflare-worker

      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: ./cloudflare-worker
          apiToken: ${{ secrets.CF_API_TOKEN }}
          wranglerVersion: "4"
          command: deploy --env production
          environment: 'production'
          secrets: |
              SIGNER_CERT
              SIGNER_KEY
              SIGNER_KEY_PASSPHRASE
              PASS_TYPE_IDENTIFIER
              TEAM_IDENTIFIER
              GOOGLE_WALLET_SERVICE_ACCOUNT_EMAIL
              GOOGLE_WALLET_SERVICE_ACCOUNT_PRIVATE_KEY
              GOOGLE_WALLET_CLASS_ID
              GOOGLE_WALLET_ALLOWED_ORIGINS
              GOOGLE_WALLET_FRONTEND_URL
        env:
          SIGNER_CERT: ${{ secrets.SIGNER_CERT }}
          SIGNER_KEY: ${{ secrets.SIGNER_KEY }}
          SIGNER_KEY_PASSPHRASE: ${{ secrets.SIGNER_KEY_PASSPHRASE }}
          PASS_TYPE_IDENTIFIER: ${{ secrets.PASS_TYPE_IDENTIFIER }}
          TEAM_IDENTIFIER: ${{ secrets.TEAM_IDENTIFIER }}
          GOOGLE_WALLET_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_WALLET_SERVICE_ACCOUNT_EMAIL }}
          GOOGLE_WALLET_SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.GOOGLE_WALLET_SERVICE_ACCOUNT_PRIVATE_KEY }}
          GOOGLE_WALLET_CLASS_ID: ${{ secrets.GOOGLE_WALLET_CLASS_ID }}
          GOOGLE_WALLET_ALLOWED_ORIGINS: ${{ secrets.GOOGLE_WALLET_ALLOWED_ORIGINS }}
          GOOGLE_WALLET_FRONTEND_URL: ${{ secrets.GOOGLE_WALLET_FRONTEND_URL }}
